<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="0" skipped="1">
  <reporter-output>
  </reporter-output>
  <suite started-at="2019-02-27T06:52:08Z" name="DataDrivenFramework" finished-at="2019-02-27T06:52:13Z" duration-ms="4269">
    <groups>
    </groups>
    <test started-at="2019-02-27T06:52:08Z" name="BankManagerLoginTest" finished-at="2019-02-27T06:52:13Z" duration-ms="4200">
      <class name="com.w2a.TestCases.BankManagerLoginTest">
        <test-method signature="BankManagerLogin()[pri:0, instance:com.w2a.TestCases.BankManagerLoginTest@7bba5817]" started-at="2019-02-27T06:52:08Z" name="BankManagerLogin" finished-at="2019-02-27T06:52:12Z" duration-ms="4126" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BankManagerLogin -->
      </class> <!-- com.w2a.TestCases.BankManagerLoginTest -->
    </test> <!-- BankManagerLoginTest -->
    <test started-at="2019-02-27T06:52:13Z" name="Add Customer Test" finished-at="2019-02-27T06:52:13Z" duration-ms="11">
      <class name="com.w2a.TestCases.AddCustomerTest">
        <test-method is-config="true" signature="SetUp()[pri:0, instance:com.w2a.TestCases.AddCustomerTest@7ce69770]" started-at="2019-02-27T06:52:01Z" name="SetUp" finished-at="2019-02-27T06:52:08Z" duration-ms="7383" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SetUp -->
        <test-method signature="addCustomer(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.w2a.TestCases.AddCustomerTest@7ce69770]" started-at="2019-02-27T06:52:13Z" name="addCustomer" data-provider="getData" finished-at="2019-02-27T06:52:13Z" duration-ms="0" status="SKIP">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[java.lang.NullPointerException]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: java.lang.NullPointerException
at org.testng.internal.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:49)
at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:131)
at org.testng.internal.Parameters.handleParameters(Parameters.java:706)
at org.testng.internal.ParameterHandler.handleParameters(ParameterHandler.java:49)
at org.testng.internal.ParameterHandler.createParameters(ParameterHandler.java:37)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:924)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.NullPointerException
at com.w2a.utilities.ExcelReader.getRowCount(ExcelReader.java:53)
at com.w2a.TestCases.AddCustomerTest.getData(AddCustomerTest.java:34)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:74)
at org.testng.internal.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:45)
... 22 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addCustomer -->
        <test-method is-config="true" signature="TearDown()[pri:0, instance:com.w2a.TestCases.AddCustomerTest@7ce69770]" started-at="2019-02-27T06:52:13Z" name="TearDown" finished-at="2019-02-27T06:52:13Z" duration-ms="208" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TearDown -->
      </class> <!-- com.w2a.TestCases.AddCustomerTest -->
    </test> <!-- Add Customer Test -->
  </suite> <!-- DataDrivenFramework -->
</testng-results>
